server:
  port: 8022
spring:
  application:
    name: lifehub-config-service
  cloud:
    loadbalancer:
      retry:
        enabled: true
  profiles:
    active: jdbc
  datasource:
    druid:
      name: dev
      url: jdbc:mysql://localhost:3306/life_config?useUnicode=true&characterEncoding=utf-8
      username: root
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat, wall
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      WebStatFilter:
        exclusions: \\*\\.js,\\*\\.gif,\\*\\.jpg,\\*\\.png,\\*\\.css,\\*\\.ico,/druid/*
      StatViewServlet:
        loginUsername: druid
        loginPassword: druid123
  jpa:
    repositories:
      enabled: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#    vhost: psp
  redis:
    database: 12
    usePool: true
    timeout: 3000
    host: localhost
    port: 6379
    pool:
      maxWait: -1
      maxIdle: 8
      minIdle: 0

eureka:
  instance:
    prefer-ip-address: true
  client:
    healthcheck:
      enabled: false
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
       defaultZone: http://localhost:9114/eureka/

logging:
  level:
    org.springframework.web: info

management:
  security:
    enabled: false